### ISSUE TITLE
SoftPWM.begin() causes inverted channels to flash LOW

### ISSUE THREAD

**Issue by per1234** [per1234/PalatisSoftPWM#1]
All pins defined as channels using SOFTPWM_DEFINE_CHANNEL_INVERT momentarily go LOW when SoftPWM.begin() is called. The reverse is not true with SOFTPWM_DEFINE_CHANNEL.

**Comment by Palatis** [comment]
call allOff() in begin()?

I didn't really test invert mode since i have a `HIGH = LED ON` setup.

**Comment by per1234** [comment]
> call allOff() in begin()?

That fixed it, thank so much Palatis! It took me a bit of testing to realize that the flash is only visually noticeable when there are a lot of PWM channels defined. I initially only had one channel in my test sketch and was starting to think I had imagined the issue. I have 15 channels on a MCU running at 8 Mhz on my actual device so it's obvious there.
